version: '3.9'
services:
  rest-csv:
    container_name: rest-csv
    build: .
    ports:
      - 8000:8000
    command: >
      bash -c "python project/manage.py migrate && python project/manage.py runserver 0.0.0.0:8000 --settings=project.settings"